version: "3.8"
services:
  api:
    container_name: movie-catalog-server-api
    build:
      dockerfile: Dockerfile
    environment:
      CONNECT_DB_HOST: db
      CONNECT_DB_PORT: 5432
      CONNECT_DB_USER: gregory
      CONNECT_DB_NAME: movie_catalog
      CONNECT_DB_PASSWORD: 1234567890
      APP_TABLE_NAME: application
      APP_VERSION_COLUMN_NAME: version
      ENCRYPTION_METHOD: aes-256-cbc
      SECRET_KEY: asdfghjkl;qwertyuiozxcvbnm,wedsa
      SECRET_IV: 19f74482j576k576
      SESSION_SECRET: 12kjn42
    ports:
      - 3000:3000
    volumes:
      - ./src:/api/src
      - ./migrations:/api/migrations
      - ./seeds:/api/seeds
    command: npm run dev
    depends_on:
      - db
  db:
    image: postgres:18.0
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_catalog
      POSTGRES_USER: gregory
      POSTGRES_PASSWORD: 1234567890
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /servers/pgadmin.json
    depends_on:
      - db
    user: '$UID:$GID'
    ports:
      - 5050:80
    volumes:
      - ./db/pgadmin/servers:/servers
      - ./db/pgadmin/pgadmin-data:/var/lib/pgadmin
